In [11]:
import pandas as pd
df = pd.read_excel("Student Awareness Survey (Responses).xlsx")
df.head()

,Timestamp,Registration Number,Email,Job role that you are interested in,What is the minimum salary of students placed through campus (In LPA..respond as a number),What is the maximum salary of students placed through campus (In LPA..respond as a number),What is the median salary of students placed through campus (In LPA..respond as a number),Which is the highest paying company that recruits from campus?,Rate your contribution towards extra curricular activities,Rate your technical competencies,What are your package expectations (LPA),Your CIA % of last semester,Your GPA of last semester,Your maximum attendance % till last semester,Internships Interests
0,2026-06-15 09:25:38.881,2547231,kunnal.kunnal@mca.christuniversity.in,Software Development Engineer (SDE),3.5,12,6.8,Akasa air,4.0,3.0,8,69,3.40,98,"AI/ML, Web Development, Data Science/Analytics..."
1,2026-06-15 09:53:53.509,2547237,omkaar.chakraborty@mca.christuniversity.in,Software Development Engineer (SDE),6,20,10,Fractal,4.0,4.0,12,75,3.69,95,"Web Development, DevOps/Cloud Computing, Mobil..."
2,2026-06-15 09:54:55.924,2547203,abhinav.jain@mca.christuniversity.in,Full Stack Developer,4,12,6.3,Akasa Air,5.0,4.0,12,82,3.41,95,"AI/ML, Web Development, Mobile App Development"
3,2026-06-15 09:55:17.320,2547228,jai.pareek@mca.christuniversity.in,Full Stack Developer,600000,1400000,800000,Akasa airlines,5.0,4.0,1200000,91,3.60,92,"Web Development, DevOps/Cloud Computing, Cyber..."
4,2026-06-15 09:55:41.848,2547241,r.karan@mca.christuniversity.in,Software Development Engineer (SDE),4,4,6,12,2.0,3.0,12,70,3.54,93,"AI/ML, Data Science/Analytics"

In [14]:
df.shape

(50, 15)

In [15]:
df.columns

Index(['Timestamp', 'Registration Number', 'Email',
       'Job role that you are interested in',
       'What is the minimum salary of students placed through campus (In LPA..respond as a number)',
       'What is the maximum salary of students placed through campus (In LPA..respond as a number)',
       'What is the median salary of students placed through campus (In LPA..respond as a number)',
       'Which is the highest paying company that recruits from campus?',
       'Rate your contribution towards extra curricular activities',
       'Rate your technical competencies',
       'What are your package expectations (LPA)',
       'Your CIA % of last semester', 'Your GPA of last semester',
       'Your maximum attendance % till last semester',
       'Internships Interests'],
      dtype='str')

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 15 columns):
 #   Column                                                                                      Non-Null Count  Dtype
---  ------                                                                                      --------------  -----
 0   Timestamp                                                                                   50 non-null     datetime64[us]
 1   Registration Number                                                                         50 non-null     int64
 2   Email                                                                                       50 non-null     str
 3   Job role that you are interested in                                                         50 non-null     str
 4   What is the minimum salary of students placed through campus (In LPA..respond as a number)  50 non-null     object
 5   What is the maximum salary of students placed through campus (In LPA..respond as a number)  50 non-null     object
 6   What is the median salary of students placed through campus (In LPA..respond as a number)   50 non-null     object
 7   Which is the highest paying company that recruits from campus?                              49 non-null     object
 8   Rate your contribution towards extra curricular activities                                  49 non-null     float64
 9   Rate your technical competencies                                                            49 non-null     float64
 10  What are your package expectations (LPA)                                                    49 non-null     object
 11  Your CIA % of last semester                                                                 50 non-null     object
 12  Your GPA of last semester                                                                   50 non-null     float64
 13  Your maximum attendance % till last semester                                                50 non-null     object
 14  Internships Interests                                                                       49 non-null     str
dtypes: datetime64[us](1), float64(3), int64(1), object(7), str(3)
memory usage: 6.0+ KB

In [17]:
df.describe()

,Timestamp,Registration Number,Rate your contribution towards extra curricular activities,Rate your technical competencies,Your GPA of last semester
count,50,5.000000e+01,49.000000,49.000000,50.000000
mean,2026-06-15 10:04:25.235739,2.547232e+06,3.489796,3.530612,3.497000
min,2026-06-15 09:25:38.881000,2.547201e+06,1.000000,2.000000,2.740000
25%,2026-06-15 09:57:03.826500,2.547217e+06,3.000000,3.000000,3.305000
50%,2026-06-15 09:59:20.247000,2.547232e+06,4.000000,3.000000,3.400000
75%,2026-06-15 10:04:23.949000,2.547246e+06,4.000000,4.000000,3.600000
max,2026-06-15 11:06:19.974000,2.547262e+06,5.000000,5.000000,8.000000
std,NaN,1.792671e+01,1.209725,0.738863,0.690865

In [18]:
df.isnull().sum()

Timestamp                                                                                     0
Registration Number                                                                           0
Email                                                                                         0
Job role that you are interested in                                                           0
What is the minimum salary of students placed through campus (In LPA..respond as a number)    0
What is the maximum salary of students placed through campus (In LPA..respond as a number)    0
What is the median salary of students placed through campus (In LPA..respond as a number)     0
Which is the highest paying company that recruits from campus?                                1
Rate your contribution towards extra curricular activities                                    1
Rate your technical competencies                                                              1
What are your package expectations (LPA)                                                      1
Your CIA % of last semester                                                                   0
Your GPA of last semester                                                                     0
Your maximum attendance % till last semester                                                  0
Internships Interests                                                                         1
dtype: int64

In [19]:
print(df["Your CIA % of last semester"].dtype)
print(df["Your GPA of last semester"].dtype)
print(df["Your maximum attendance % till last semester"].dtype)

object
float64
object

In [20]:
df["Your CIA % of last semester"] = pd.to_numeric(
    df["Your CIA % of last semester"],
    errors="coerce"
)

df["Your GPA of last semester"] = pd.to_numeric(
    df["Your GPA of last semester"],
    errors="coerce"
)

df["Your maximum attendance % till last semester"] = pd.to_numeric(
    df["Your maximum attendance % till last semester"],
    errors="coerce"
)

In [21]:
df = df.dropna(
    subset=[
        "Your CIA % of last semester",
        "Your GPA of last semester",
        "Your maximum attendance % till last semester"
    ]
)

In [22]:
df = df.drop_duplicates()

In [23]:
df.shape

(48, 15)

In [24]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [25]:
X = df[["Your CIA % of last semester"]]

y = df["Your GPA of last semester"]

In [26]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [ ]:
#this is where the machine learns, tries to find out the best slope , best intercept
model = LinearRegression()

In [28]:
model.fit(X_train, y_train)

LinearRegression()

In [29]:
print("Slope =", model.coef_[0])
print("Intercept =", model.intercept_)

Slope = -0.0047202149867046645
Intercept = 3.798379798593148

In [30]:
y_pred = model.predict(X_test)

print(y_pred)

[3.46324453 3.4690032  3.46796475 3.44436367 3.45852432 3.45852432
 3.43020303 3.46796475 3.46796475 3.46796475]

In [31]:
comparison = pd.DataFrame({
    "Actual GPA": y_test,
    "Predicted GPA": y_pred
})

comparison.head()

    Actual GPA  Predicted GPA
28        3.33       3.463245
42        3.30       3.469003
27        3.00       3.467965
45        3.66       3.444364
25        3.55       3.458524

In [ ]:


X = df[["Your maximum attendance % till last semester"]]

y = df["Your GPA of last semester"]

In [33]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [34]:
model2 = LinearRegression()

In [35]:
model2.fit(X_train, y_train)

LinearRegression()

In [36]:
print("Slope =", model2.coef_[0])
print("Intercept =", model2.intercept_)

Slope = -0.006208685898159074
Intercept = 3.995388062618632

In [37]:
y_pred2 = model2.predict(X_test)

print(y_pred2)

[3.38072816 3.42418896 3.41798027 3.4055629  3.41798027 3.37451947
 3.4055629  3.4055629  3.41798027 3.39935422]

In [38]:
comparison2 = pd.DataFrame({
    "Actual GPA": y_test,
    "Predicted GPA": y_pred2
})

comparison2.head()

    Actual GPA  Predicted GPA
28        3.33       3.380728
42        3.30       3.424189
27        3.00       3.417980
45        3.66       3.405563
25        3.55       3.417980

In [39]:
x = df["Your CIA % of last semester"]

y = df["Your GPA of last semester"]

In [40]:
x_mean = x.mean()
y_mean = y.mean()

print("X Mean =", x_mean)
print("Y Mean =", y_mean)

X Mean = 59.21564791666666
Y Mean = 3.5031249999999994

In [41]:
m = ((x - x_mean) * (y - y_mean)).sum() / ((x - x_mean)**2).sum()

print("Slope =", m)

Slope = -0.004928373328689654

In [42]:
b = y_mean - (m * x_mean)

print("Intercept =", b)

Intercept = 3.7949618198335764

In [43]:
print(f"GPA = {b} + ({m}) * CIA")

GPA = 3.7949618198335764 + (-0.004928373328689654) * CIA

In [44]:
manual_pred = b + (m * X_test.squeeze())

print(manual_pred.head())

28    3.307053
42    3.341551
27    3.336623
45    3.326766
25    3.336623
Name: Your maximum attendance % till last semester, dtype: float64

In [45]:
comparison_ols = pd.DataFrame({
    "Scikit Learn": y_pred,
    "Manual OLS": manual_pred
})

comparison_ols.head()

    Scikit Learn  Manual OLS
28      3.463245    3.307053
42      3.469003    3.341551
27      3.467965    3.336623
45      3.444364    3.326766
25      3.458524    3.336623

In [46]:
X_cia = df[["Your CIA % of last semester"]]
y = df["Your GPA of last semester"]

In [47]:
from sklearn.model_selection import train_test_split

X_train_cia, X_test_cia, y_train_cia, y_test_cia = train_test_split(
    X_cia,
    y,
    test_size=0.2,
    random_state=42
)

In [48]:
manual_pred = b + (m * X_test_cia.squeeze())

In [49]:
comparison_ols = pd.DataFrame({
    "Scikit Learn": y_pred,
    "Manual OLS": manual_pred
})

comparison_ols.head()

    Scikit Learn  Manual OLS
28      3.463245    3.445047
42      3.469003    3.451060
27      3.467965    3.449976
45      3.444364    3.425334
25      3.458524    3.440119

In [50]:
import pickle

params = {
    "slope": model.coef_[0],
    "intercept": model.intercept_
}

with open("linear_regression_weights.pkl", "wb") as file:
    pickle.dump(params, file)

print("Parameters saved successfully!")

Parameters saved successfully!

In [51]:
with open("linear_regression_weights.pkl", "rb") as file:
    loaded_params = pickle.load(file)

print(loaded_params)

{'slope': np.float64(-0.0047202149867046645), 'intercept': np.float64(3.798379798593148)}

In [52]:
cia = 70

predicted_gpa = loaded_params["intercept"] + (
    loaded_params["slope"] * cia
)

print("Predicted GPA =", predicted_gpa)

Predicted GPA = 3.467964749523821